.circleci/config.yml
lib/telemetry_metrics_statsd.ex
lib/telemetry_metrics_statsd/event_handler.ex
lib/telemetry_metrics_statsd/formatter.ex
lib/telemetry_metrics_statsd/packet.ex
mix.exs
mix.lock
test/telemetry_metrics_statsd/packet_test.exs
test/telemetry_metrics_statsd_test.exs

This is especially important in case of UDP, where each packet needs to fit into a single IP datagram (there is no control flow mechanism to ensure that packets are "whole").
I've also updated to the newest Telemetry.Metrics and made some changes so that the tests run on Elixir 1.5.

 Allow to configure Maximum Transmission Units

---

lib/telemetry_metrics_statsd.ex

I tried to explain the behaviour of the counter metric, i.e. why it is always incremented by 1. 
@haljin does it make a bit more sense now? Would you add anything more?

Clarify the behaviour of the counter metric

---

lib/telemetry_metrics_statsd.ex
lib/telemetry_metrics_statsd/formatter.ex
mix.exs
mix.lock
test/telemetry_metrics_statsd_test.exs

This adds support for summary metric introduced in Telemetry.Metrics v0.3.0. Also, the requirement for `telemetry_metrics` dependency has been bumped.

Support summary metric

---

lib/telemetry_metrics_statsd.ex
lib/telemetry_metrics_statsd/event_handler.ex
test/telemetry_metrics_statsd_test.exs

I wrote this for myself, and I don't know if you want something like this in the library or if other people would find it useful, but I figured I would give you the option either way.
I keep finding myself wanting to easily include information like app environment with every metric, and I don't particularly want to be making a `System.get_env` call or storing it in an agent (or `ets`), and want it quickly available each time a metric gets published. This seemed like a reasonable way to do that.
If you might want to include this and want/need edits, I'm happy to make those. If you don't want this, feel free to close the PR.
Thanks for the library, saved me a bunch of time :)

allow default tags

---

CHANGELOG.md
README.md
mix.exs

Chores before a new release: bumped version in mix.exs and a README, updated the change log.
Let's merge this after #20

Release 0.3.0

---

README.md
lib/telemetry_metrics_statsd.ex
lib/telemetry_metrics_statsd/udp.ex

I am using TelemetryMetricsStatsd to send Ecto query telemetry. I
noticed this slowed down some of our calls. One of the more expensive
operations is apparently :inet_udp.getaddr/1. However, there is no need
to look up localhost using this function. I have included some benchmark
information collected with fprof below.
When using localhost:
```
TelemetryMetricsStatsd.UDP.send/2                                   12      12.319       0.088
:gen_udp.send/4                                                   12      12.319       0.088  <--
:inet_db.lookup_socket/1                                        12       0.051       0.034
:inet_udp.send/4                                                12       0.622       0.023
:inet_udp.getaddr/1                                             12 …
```

Allow sending to IPs and default to 127.0.0.1

---

lib/telemetry_metrics_statsd.ex
lib/telemetry_metrics_statsd/formatter/datadog.ex
lib/telemetry_metrics_statsd/formatter/standard.ex
test/telemetry_metrics_statsd/formatter/datadog_test.exs
test/telemetry_metrics_statsd/formatter/standard_test.exs

The counter metric only supports incrementing by 1, but often there is need to increment a counter by the metric value. This adds that support to the standard and Datadog sum metric with a custom `report_as` option as discussed in #27 and based on the work in #25. 
In the case of a negative value, the metric will be dropped, and logged, as negative counters are not supported. (@arkgil please check that part, I've set it up to format the metric as `""` in this case, but if there is a better way to drop the metric then I'm happy to modify).
Docs and tests have been updated as well
Fixes #27

Support using the sum metric for StatsD and Datadog counters

---

README.md
lib/telemetry_metrics_statsd/formatter/datadog.ex
mix.lock
test/telemetry_metrics_statsd/formatter/datadog_test.exs

Support Datadog distributions metric in Datadog formatter

---

lib/telemetry_metrics_statsd.ex
lib/telemetry_metrics_statsd/udp.ex
test/telemetry_metrics_statsd_test.exs

Adds Unix domain socket support by extending the reporter configuration options with `socket_path` and changing how the connection is opened and data is sent based on its presence.
This is a draft - let me know if the initial idea looks good and I will continue with updating the docs. In the meantime, I'll do some testing with the DogStatsD agent.
Fixes #17.

Support Unix Domain Sockets

---

lib/telemetry_metrics_statsd.ex
lib/telemetry_metrics_statsd/udp.ex
test/telemetry_metrics_statsd_test.exs

This makes sure the old, failing socket gets closed after a new socket gets opened. Fixes #39.

Close old socket after opening a new one

---

.circleci/config.yml

1.11 is on the way, and we need to bump the version to satisfy dependency requirement in #41

Bump the lower Elixir version on CI to 1.7.4

---

lib/telemetry_metrics_statsd.ex
lib/telemetry_metrics_statsd/formatter/datadog.ex
test/telemetry_metrics_statsd/formatter/datadog_test.exs

Previously, sum updates were reported as gauge increments/decrements. However, this sort of metric updates do not allow to view the sum of measurements in the DataDog dashboard, because with gauges, only the last measurement in the flush interval is shown.
With counter, it is possible to view the total sum of measurement values in a flush interval. To make sure that the actual sum and not a rate is displayed in the DataDog dashboard, the [`as_count()`](docs.datadoghq.com/developers/metrics/type_modifiers/?tab=rate#in-application-modifiers) modifier should be used.
While this is a breaking change, the previous behaviour was simply wrong.

Always report sum as a counter with DataDog formatter

---

lib/telemetry_metrics_statsd/event_handler.ex
lib/telemetry_metrics_statsd/formatter/standard.ex
test/telemetry_metrics_statsd/formatter/datadog_test.exs
test/telemetry_metrics_statsd/formatter/standard_test.exs
test/telemetry_metrics_statsd_test.exs

With standard StatsD formatter, if the tag value is empty or missing,
the metric update is not sent at all, because the formatted metric name
would be malformed.
With DataDog formatter, an empty tag value is sent.
Closes #43

Allow empty and missing tag values

---

lib/telemetry_metrics_statsd/event_handler.ex
mix.lock
test/telemetry_metrics_statsd_test.exs

There was no need to bump Telemetry.Metrics version requirement, since we can still work with the old version.

Support 2-arity measurement functions

---

lib/telemetry_metrics_statsd.ex
test/telemetry_metrics_statsd_test.exs

This improves the reporter throughput 20 times.

Resolve host on reporter start

---

lib/telemetry_metrics_statsd/udp.ex

There is no consistent difference in performance for active vs
non-active sockets, so for the piece of mind we might make them non-active.

Set active: false on UDP sockets

---

mix.exs

The reporter has been using telemetry since the beginning, but it only had it in deps transitively via telemetry_metrics.

Add telemetry to dependencies

---

lib/telemetry_metrics_statsd/packet.ex

```
[error] Handler {TelemetryMetricsStatsd.EventHandler, #PID<0.838.0>, [:nex, :repo, :query]} has failed and has been detached. Class=:error
Reason=%RuntimeError{message: "Binary size exceeds the provided maximum packet size"}
```
It took me a while to figure this could be increased by [mtu](https://github.com/statsd/statsd/blob/9cf77d87855bcb69a8663135f59aa23825db9797/docs/metric_types.md#multi-metric-packets). I Hope this help at least to figure how to work around the error.

Improve binary maximum packet size error message

---

lib/telemetry_metrics_statsd/options.ex
mix.exs
mix.lock

Fixes #68 
This PR replaces the nimble_options `:replace_to` with a custom function which achieves the same thing as this option is now deprecated in nimble_options 0.4.
I've also upgraded nimble_options to 0.4.
We had an issue with running the tests locally as it seems the `capture_log`s in some tests aren't capturing long enough to capture the expected error logging. Adding `Process.sleep` fixes those tests but of course that isn't an ideal solution so I've left the tests as is for now.

Replace NimbleOptions `rename_to` with a custom function

---

.github/workflows/test.yml
test/telemetry_metrics_statsd_test.exs

The CI fails on the main branch.
- Fix GitHub Actions
- Use setup-beams
- https://github.com/actions/setup-elixir is archived.
- https://github.com/erlef/setup-elixir is redirected to https://github.com/erlef/setup-beam
- Use ubuntu-20.04 because ubuntu-latest does not have old Erlang/OTP and Elixir versions
- References:
- https://repo.hex.pm/builds/otp/ubuntu-20.04/builds.txt
- https://repo.hex.pm/builds/otp/ubuntu-22.04/builds.txt
- https://github.com/beam-telemetry/telemetry_metrics/pull/104
- Fix flaky tests
- See the comment on the tests.
I confirmed that the CI was passed at the forked repository.
See https://github.com/mopp/telemetry_metrics_statsd/pull/2

Fix CI and flaky tests

---

lib/telemetry_metrics_statsd.ex
lib/telemetry_metrics_statsd/options.ex
lib/telemetry_metrics_statsd/udp.ex
test/telemetry_metrics_statsd_test.exs

Fixes #78
I'm using this to be able to send metrics over IPv6 on fly.io through WireGuard

Allow for inet6 option

---

lib/telemetry_metrics_statsd/formatter/standard.ex
test/telemetry_metrics_statsd/formatter/standard_test.exs
test/telemetry_metrics_statsd_test.exs

Fix handling of empty and missing tag values with standard formatter

---

lib/telemetry_metrics_statsd/packet.ex

Update binary size exceeds message to include size values and avoid guessing max mtu size needed

Update binary size exceeds message 

---

lib/telemetry_metrics_statsd.ex

This PR is much less ambitious than #94 (and so I expect it would be an easier merge). In this case, we just fix the issue when the process is already started, but an error in the resolution of the hostname leads to an incorrect internal state.
Without this patch, the `new_state` will be `:ok`, as that is the return from the logger function.
Afterwards, when going to the `terminate` callback, then we try to call `EventHandler.detach(state.handler_ids)`, which translates to `EventHandler.detach(:ok.handler_ids)` and fails.

Fix incorrect state when hostname resolution fails

---

mix.exs
mix.lock

`telemetry_metrics` lib has released v1.0 ([ref](https://github.com/beam-telemetry/telemetry_metrics/blob/main/CHANGELOG.md#100)) and there is no change in API.
however, `telemetry_metrics_statsd` still depends on v0.6. just bump the mix file.
this PR should also close issue 91 https://github.com/beam-telemetry/telemetry_metrics_statsd/issues/91

issue #91 chore: bump telemetry_metrics from 0.6 -> 1.0. no breaking change
